export const sampleChats = [
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Angela_White"],
    name: "Leana Lovings",
    _id: "1",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    name: "Riley Reid",
    _id: "2",
    groupChat: false,
    members: ["1", "2"],
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Riley_Reid"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Jenna_Jameson"],
    name: "Jenna Jameson",
    _id: "3",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Sasha_Grey"],
    name: "Sasha Grey",
    _id: "4",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Brandi_Love"],
    name: "Brandi Love",
    _id: "5",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Nicole_Aniston"],
    name: "Nicole Aniston",
    _id: "6",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Abella_Danger"],
    name: "Abella Danger",
    _id: "7",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Tori_Black"],
    name: "Tori Black",
    _id: "8",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Angela_White"],
    name: "Leana Lovings",
    _id: "9",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Riley_Reid"],
    name: "Riley Reid",
    _id: "10",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Jenna_Jameson"],
    name: "Jenna Jameson",
    _id: "11",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Sasha_Grey"],
    name: "Sasha Grey",
    _id: "12",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Brandi_Love"],
    name: "Brandi Love",
    _id: "13",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Nicole_Aniston"],
    name: "Nicole Aniston",
    _id: "14",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Abella_Danger"],
    name: "Abella Danger",
    _id: "15",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Tori_Black"],
    name: "Tori Black",
    _id: "16",
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Angela_White"],
    name: "Leana Lovings",
    _id: "17",
    groupChat: false,
    members: ["1", "2"],
  },
];
export const sampleUsers = [
  {
    name: "Angela White",
    _id: "1",
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Angela_White"],
  },
  {
    name: "Riley Reid",
    _id: "2",
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Riley_Reid"],
  },
  {
    name: "Jenna Jameson",
    _id: "3",
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Jenna_Jameson"],
  },
  {
    name: "Sasha Grey",
    _id: "4",
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Sasha_Grey"],
  },
  {
    name: "Brandi Love",
    _id: "5",
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Brandi_Love"],
  },
  {
    name: "Nicole Aniston",
    _id: "6",
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Nicole_Aniston"],
  },
  {
    name: "Abella Danger",
    _id: "7",
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Abella_Danger"],
  },
  {
    name: "Tori Black",
    _id: "8",
    avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Tori_Black"],
  },
];
export const sampleNotifications = [
  {
    sender: {
      name: "Angela White",
      avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Angela_White"],
    },
    _id: "1",
  },
  {
    sender: {
      name: "Riley Reid",
      avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Riley_Reid"],
    },
    _id: "2",
  },
  {
    sender: {
      name: "Jenna Jameson",
      avatar: ["https://api.dicebear.com/8.x/adventurer/svg?seed=Jenna_Jameson"],
    },
    _id: "3",
  },
];
export const sampleMessages = [
  {
    attachments: [
      {
        public_id: "bhbvsd",
        url: "https://picsum.photos/200/300",
      },
    ],
    content: "Hello, how are you?",
    _id: "dftgukfabvklfv",
    sender: {
      _id: "gafvkcvl",
      name: "Krishna Kumar",
    },
    chat: "chatID",
    createdAt: "2024-04-01T14:48:00.000Z",
  },
  {
    attachments: [
      {
        public_id: "bhbvsdvd",
        url: "https://picsum.photos/200/300",
      },
    ],
    content: "Fine, how are you?",
    _id: "dftgukfabvklfvwwvv",
    sender: {
      _id: "user._id",
      name: "Leana Lovings",
    },
    chat: "chatID",
    createdAt: "2024-04-01T14:48:00.000Z",
  }
];
export const sampleDashboardData = {
  users: [
    {
      _id: 1,
      avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Angela_White",
      username: "Angela White",
      name: "Angela White",
      email: "angela@kmail.com",
      friends: 10,
      groups: 5,
      joinedAt: "2024-04-01T14:48:00.000Z",
    },
    {
      _id: 2,
      avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Riley_Reid",
      username: "Riley Reid",
      name: "Riley Reid",
      email: "riley@kmail.com",
      friends: 10,
      groups: 5,
      joinedAt: "2024-04-01T14:48:00.000Z",
    },
    {
      _id: 3,
      avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Jenna_Jameson",
      username: "Jenna Jameson",
      name: "Jenna Jameson",
      email: "Jenna@kmail.com",
      friends: 10,
      groups: 5,
      joinedAt: "2024-04-01T14:48:00.000Z",
    },
    {
      _id: 4,
      avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Lisa_Ann",
      username: "Lisa Ann",
      name: "Lisa Ann",
      email: "lisa@kmail.com",
      friends: 8,
      groups: 3,
      joinedAt: "2024-04-02T10:22:00.000Z",
    },
    {
      _id: 5,
      avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Sasha_Grey",
      username: "Sasha Grey",
      name: "Sasha Grey",
      email: "sasha@kmail.com",
      friends: 12,
      groups: 7,
      joinedAt: "2024-04-03T16:15:00.000Z",
    },
    {
      _id: 6,
      avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Mia_Khalifa",
      username: "Mia Khalifa",
      name: "Mia Khalifa",
      email: "mia@kmail.com",
      friends: 15,
      groups: 4,
      joinedAt: "2024-04-04T09:58:00.000Z",
    },
    {
      _id: 7,
      avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Abella_Danger",
      username: "Abella Danger",
      name: "Abella Danger",
      email: "abella@kmail.com",
      friends: 9,
      groups: 6,
      joinedAt: "2024-04-05T11:30:00.000Z",
    },
    {
      _id: 8,
      avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Madison_Ivy",
      username: "Madison Ivy",
      name: "Madison Ivy",
      email: "madison@kmail.com",
      friends: 11,
      groups: 8,
      joinedAt: "2024-04-06T13:20:00.000Z",
    },
    {
      _id: 9,
      avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Kendra_Sunderland",
      username: "Kendra Sunderland",
      name: "Kendra Sunderland",
      email: "kendra@kmail.com",
      friends: 13,
      groups: 3,
      joinedAt: "2024-04-07T15:10:00.000Z",
    },
    {
      _id: 10,
      avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Jesse_Jane",
      username: "Jesse Jane",
      name: "Jesse Jane",
      email: "jesse@kmail.com",
      friends: 14,
      groups: 5,
      joinedAt: "2024-04-08T17:00:00.000Z",
    },
  ]
};